### PR TITLE
Fixes displaying avatar instead of login, mobile

### LINKED ISSUE #20: Avatar display, mobile version

### PR DESCRIPTION
**Pull request by jgrgurovic**
**Summary:**

- [ ] When a user logs in, their avatar is displayed instead of the login link.
- [ ] Enhanced the mobile header with specific features for smaller screen sizes.

**! For the Reviewer:**

In this pull request, I made the following changes:

- Replaced the login link with the user's avatar upon logging in to provide a better user experience.

- Implemented mobile-specific enhancements for the header. To achieve this, I mixed `navigation.module.css` with Tailwind CSS (which I know is a no no 😅). This decision was made because Tailwind CSS follows a 'mobile-first' approach, and I needed to cater to screen sizes smaller than 'md.' This allowed me to achieve the desired mobile header behavior efficiently.
If there is a better way to do this do tell, as this is what was suggested to me while digging around

### CODE REVIEW

File: src/components/Navigation/NavigationHeader.tsx [hunk 1]
```diff
@@ -1,30 +1,49 @@
...
+          width={150}
+          height={120}
+          className={styles.logo}
+        />
+        <div className="hidden md:flex md:relative items-center ">
+          <div className="ml-auto mr-4">
+            {token ? (
+              <Link href="/profile" className="text-xl text-white">
+                {user ? (
+                  <Image
```
Comment (kula124) [inline src/components/Navigation/NavigationHeader.tsx]: I suppose both `token` and `user` checks can be replaced by a single `user` or `token` check.
Maybe even a variable.
You can replace `checkMe ? element : null` with `checkMe && element`. There are small differences and your expression is "more correct" but it's also harder to read so, your call.
Example with variable
```tsx
const isLoggedIn: boolean = user && token

return(
 ...
<div className="ml-auto mr-4">
 {isLoggedIn && (
   <Link href="/profile" className="text-xl text-white">
     <Image
        src={user.avatar}
        alt="User Avatar"
        width={50}
        height={50}
        className="rounded-full border-2" 
    />
  </Link>
...
)
```

Seems redundant? 
You can make it so that `useAuth` gives you the user or `null` if not logged in. Then you don't need both token and user object but just user object to check. In that case replace `isLoggedIn` with `user`

File: src/components/Navigation/NavigationHeader.tsx [hunk 2]
```diff
@@ -1,30 +1,49 @@
...
+import styles from "./navigation.module.css"
+import Logo from "../../../public/images/logos/logo_tc.png"
 const NavigationHeader = () => {
+  const { token, user } = useAuth()
+
   return (
-    <div className="bg-black py-1">
-      <div className="container mx-auto flex justify-between items-center py-2">
+    <div className={`${styles.mobile_nav} ${styles.nav}`}>
+      <div className="container mx-auto flex justify-between items-center py-2 ">
```
Comment (kula124) [inline src/components/Navigation/NavigationHeader.tsx]: Mixing modules and TW is not a big "no no", just makes it harder to read and maintain the code.
You can use Chat GPT to transform your SCSS file to TW or vice versa if this is something you want to fix :)

File: src/hooks/useAuth.ts [hunk 3]
```diff
@@ -11,6 +12,7 @@ const useAuth = () => {
   const [user, setUser] = useState<User | null>(null)
   const [loading, setLoading] = useState(true)
   const [error, setError] = useState<UseUserError | null>(null)
+  const [token, setToken] = useState<string | null>(null);
```
Comment (kula124) [inline src/hooks/useAuth.ts]: Why do we need token in state 🤔

File: src/components/Navigation/NavigationBar.tsx [hunk 4]
```diff
@@ -2,22 +2,24 @@
 import React from "react"
 import Link from "next/link"
 import { usePathname } from "next/navigation"
-import navTabs from "../../../constants/navbar"
+import navTabs from "../../../config/navbar"
```
Comment (ilovric00) [inline src/components/Navigation/NavigationBar.tsx]: use absolute import

File: src/components/Navigation/NavigationHeader.tsx (hunk 2 above)
Comment (ilovric00) [reply src/components/Navigation/NavigationHeader.tsx]: I agree

File: src/components/Navigation/NavigationHeader.tsx [hunk 5]
```diff
@@ -1,30 +1,49 @@
...
           </div>
-        </form>
-        <div className="ml-auto">
-          <Link href="/login" className="text-xl text-white">
-            Log In
-          </Link>
         </div>
       </div>
+      <div className="hidden md:flex md:relative items-center">
+        <hr className=" lg:visible border-t-1 border-white w-10/12 mx-auto opacity-100" />
```
Comment (ilovric00) [inline src/components/Navigation/NavigationHeader.tsx]: you have an empty spaces before lg:visible :)

File: src/components/Navigation/navigation.module.css [hunk 6]
```diff
@@ -0,0 +1,18 @@
+@media screen and (max-width:768px){
+.mobile_nav{
+    position: fixed;
+    bottom: 10px;
+    z-index: 40;
+    left: 50%;
+    transform: translateX(-50%);
+}
+.logo{
```
Comment (ilovric00) [inline src/components/Navigation/navigation.module.css]: blank line

**Review by ilovric00 — CHANGES_REQUESTED** [review]

File: src/components/Navigation/NavigationHeader.tsx (hunk 2 above)
Comment (jgrgurovic) [reply src/components/Navigation/NavigationHeader.tsx]: Switched it to TW in the end

File: src/hooks/useAuth.ts (hunk 3 above)
Comment (jgrgurovic) [reply src/hooks/useAuth.ts]: I initially used useState for 'token' because I needed it(as you can see in the code from NavigationHeader above) to check if a user is authenticated in my code. However, when I attempted to include 'token' in the return value of the useAuth hook, I faced an error. To resolve this issue, I used useState to store 'token' in the component's state, so it could be accessed and returned. But now upon your feedback, I opted out for only using 'user' to check auth, so  I subsequently removed token from state as I no longer need it for this purpose.

**Review by ilovric00 — APPROVED** [review]

**Review by kula124 — APPROVED** [review]
